window.JOBS_DATA = [
  {
    id: "j1",
    title: "SDE Intern",
    company: "Amazon",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Python", "Data Structures", "Algorithms"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.amazon.jobs/en/jobs/1234567/sde-intern",
    description: "Join Amazon's internship program to work on real-world projects. You'll collaborate with senior engineers and contribute to services used by millions. Mentorship and learning opportunities included."
  },
  {
    id: "j2",
    title: "Graduate Engineer Trainee",
    company: "TCS",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "Spring Boot"],
    source: "Naukri",
    postedDaysAgo: 3,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.naukri.com/tcs-graduate-engineer-trainee-123",
    description: "TCS GET program offers structured training and placement in emerging technologies. Work on client projects across banking, retail, and healthcare domains. Comprehensive onboarding and certification support."
  },
  {
    id: "j3",
    title: "Junior Backend Developer",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Node.js", "PostgreSQL", "Redis", "Go"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "6–10 LPA",
    applyUrl: "https://jobs.razorpay.com/junior-backend-123",
    description: "Build scalable payment infrastructure at one of India's fastest-growing fintechs. You'll work on APIs powering millions of transactions. Strong mentorship from senior engineers."
  },
  {
    id: "j4",
    title: "Frontend Intern",
    company: "Freshworks",
    location: "Chennai",
    mode: "Remote",
    experience: "Fresher",
    skills: ["React", "JavaScript", "CSS", "HTML"],
    source: "Indeed",
    postedDaysAgo: 2,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.indeed.com/viewjob?jk=freshworks-frontend-intern-456",
    description: "Work on Freshworks product interfaces used by SMBs worldwide. Build responsive, accessible UIs with modern React patterns. Join a design-led engineering culture."
  },
  {
    id: "j5",
    title: "QA Intern",
    company: "Infosys",
    location: "Pune",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Selenium", "Manual Testing", "SQL", "JIRA"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://career.infosys.com/job-detail/qa-intern-pune-789",
    description: "Infosys QA internship focuses on test automation and quality assurance practices. Work on enterprise software testing cycles. Exposure to Agile and DevOps methodologies."
  },
  {
    id: "j6",
    title: "Data Analyst Intern",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "SQL", "Excel", "Tableau"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://careers.swiggy.com/intern/data-analyst-101",
    description: "Analyze delivery and restaurant data to drive business decisions. Build dashboards and reports for operations teams. Work with large-scale datasets in a data-first culture."
  },
  {
    id: "j7",
    title: "Java Developer (0-1)",
    company: "Wipro",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring", "Hibernate", "REST APIs"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "3–5 LPA",
    applyUrl: "https://careers.wipro.com/java-developer-0-1-hyd",
    description: "Join Wipro's Java practice to develop enterprise applications. Work on microservices and cloud-native solutions. Training in Spring Boot and cloud technologies provided."
  },
  {
    id: "j8",
    title: "Python Developer (Fresher)",
    company: "Zoho",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "Django", "PostgreSQL", "Linux"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.zoho.com/careers/python-fresher-chennai.html",
    description: "Zoho builds its entire product suite in-house. Freshers work on real projects from day one. Strong engineering culture with minimal hierarchy. Campus-like environment in Chennai."
  },
  {
    id: "j9",
    title: "React Developer (1-3)",
    company: "PhonePe",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "TypeScript", "Redux", "Node.js"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.phonepe.com/careers/react-developer-123",
    description: "Build consumer-facing payments and fintech products at scale. Work with React and modern frontend tooling. Millions of users interact with what you build daily."
  },
  {
    id: "j10",
    title: "SDE Intern",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Kotlin", "Android", "System Design"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.indeed.com/viewjob?jk=flipkart-sde-intern-202",
    description: "Flipkart's internship program gives exposure to e-commerce at scale. Work on catalog, search, or logistics systems. PPO opportunities for top performers."
  },
  {
    id: "j11",
    title: "Graduate Engineer Trainee",
    company: "Accenture",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "Fresher",
    skills: [".NET", "Java", "Cloud", "Agile"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.accenture.com/in-en/careers/get-program",
    description: "Accenture's GET program trains you in full-stack development and cloud. Rotate across projects in different industries. Global client exposure and certifications."
  },
  {
    id: "j12",
    title: "Junior Backend Developer",
    company: "CRED",
    location: "Bangalore",
    mode: "Remote",
    experience: "0-1",
    skills: ["Python", "Django", "AWS", "PostgreSQL"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "6–10 LPA",
    applyUrl: "https://cred.club/careers/junior-backend-303",
    description: "Build backend systems for India's premium rewards platform. Work on APIs, data pipelines, and microservices. Small team, high ownership, fast iteration."
  },
  {
    id: "j13",
    title: "Frontend Intern",
    company: "Juspay",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["JavaScript", "React", "Web Performance"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "₹25k–₹45k/month Internship",
    applyUrl: "https://juspay.io/careers/frontend-intern",
    description: "Juspay powers payments for major apps. Work on SDKs and checkout experiences. Focus on performance and reliability at transaction scale."
  },
  {
    id: "j14",
    title: "Data Analyst Intern",
    company: "Capgemini",
    location: "Pune",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Power BI", "SQL", "Statistics"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "₹18k–₹35k/month Internship",
    applyUrl: "https://www.capgemini.com/in-en/careers/data-analyst-intern",
    description: "Capgemini's data practice works with Fortune 500 clients. Build analytics solutions and dashboards. Exposure to data engineering and ML pipelines."
  },
  {
    id: "j15",
    title: "Java Developer (0-1)",
    company: "Cognizant",
    location: "Chennai",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "Kafka", "Docker"],
    source: "Indeed",
    postedDaysAgo: 2,
    salaryRange: "3–5 LPA",
    applyUrl: "https://careers.cognizant.com/java-0-1-chennai",
    description: "Cognizant's digital engineering group builds modern Java applications. Work on microservices and event-driven systems. Client projects in healthcare and finance."
  },
  {
    id: "j16",
    title: "React Developer (1-3)",
    company: "Paytm",
    location: "Noida",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "JavaScript", "Redux", "REST APIs"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "10–18 LPA",
    applyUrl: "https://paytm.com/careers/react-developer-noida",
    description: "Build Paytm's consumer and merchant web experiences. Work on payments, lending, and commerce products. Large scale, high traffic, impactful work."
  },
  {
    id: "j17",
    title: "SDE Intern",
    company: "IBM",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Python", "Cloud", "Machine Learning"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.ibm.com/careers/internship-sde-bangalore",
    description: "IBM internships focus on AI, cloud, and enterprise software. Work on Watson or hybrid cloud products. Mentorship from experienced researchers and engineers."
  },
  {
    id: "j18",
    title: "Graduate Engineer Trainee",
    company: "Oracle",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "Cloud", "Networking"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.oracle.com/in/corporate/careers/get-bangalore",
    description: "Oracle's GET program trains you on database and cloud technologies. Work on Oracle Cloud Infrastructure or database products. Strong technical foundation."
  },
  {
    id: "j19",
    title: "Junior Backend Developer",
    company: "Unacademy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Node.js", "MongoDB", "Redis", "AWS"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "6–10 LPA",
    applyUrl: "https://unacademy.com/careers/junior-backend-404",
    description: "Build backend systems for India's largest learning platform. Work on live classes, content delivery, and user engagement. Fast-paced edtech environment."
  },
  {
    id: "j20",
    title: "QA Intern",
    company: "SAP",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["SAP", "Automation", "SQL", "Testing"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://jobs.sap.com/qa-intern-bangalore",
    description: "SAP offers QA internships on enterprise software. Learn test automation for SAP products. Exposure to ERP and cloud platforms."
  },
  {
    id: "j21",
    title: "Python Developer (Fresher)",
    company: "Postman",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Python", "APIs", "PostgreSQL"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.postman.com/careers/python-fresher",
    description: "Postman is the API platform. Freshers contribute to core product and integrations. Work on developer tools used by millions globally."
  },
  {
    id: "j22",
    title: "React Developer (1-3)",
    company: "Dunzo",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "React Native", "TypeScript"],
    source: "Indeed",
    postedDaysAgo: 6,
    salaryRange: "10–18 LPA",
    applyUrl: "https://dunzo.com/careers/react-developer",
    description: "Build Dunzo's consumer and partner apps. Work on hyperlocal delivery at scale. Mobile-first React and React Native development."
  },
  {
    id: "j23",
    title: "SDE Intern",
    company: "Meesho",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Kotlin", "Android", "SQL"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://meesho.com/careers/sde-intern-505",
    description: "Meesho's reseller platform serves millions. Interns work on catalog, orders, or growth systems. Strong engineering culture and PPO pipeline."
  },
  {
    id: "j24",
    title: "Graduate Engineer Trainee",
    company: "Dell",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Python", "Cloud", "Networking"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "3–5 LPA",
    applyUrl: "https://jobs.dell.com/get-bangalore",
    description: "Dell Technologies GET program covers infrastructure and cloud. Work on storage, servers, or networking products. Global team collaboration."
  },
  {
    id: "j25",
    title: "Junior Backend Developer",
    company: "ShareChat",
    location: "Bangalore",
    mode: "Remote",
    experience: "0-1",
    skills: ["Go", "Python", "Redis", "Kafka"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "6–10 LPA",
    applyUrl: "https://sharechat.com/careers/junior-backend-606",
    description: "ShareChat serves India's vernacular internet. Build backend for content, recommendations, and social features. High scale, real-time systems."
  },
  {
    id: "j26",
    title: "Frontend Intern",
    company: "Slice",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "TypeScript", "CSS"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "₹22k–₹45k/month Internship",
    applyUrl: "https://slice.it/careers/frontend-intern",
    description: "Slice is a fintech for young India. Work on card and rewards web experiences. Modern React stack, design-driven development."
  },
  {
    id: "j27",
    title: "Data Analyst Intern",
    company: "Policybazaar",
    location: "Gurgaon",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["SQL", "Excel", "Python", "Analytics"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "₹20k–₹38k/month Internship",
    applyUrl: "https://policybazaar.com/careers/data-intern",
    description: "Policybazaar's data team drives insurance product decisions. Build reports and analyses for pricing and acquisition. Exposure to insurance domain."
  },
  {
    id: "j28",
    title: "Java Developer (0-1)",
    company: "HCL",
    location: "Noida",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring", "Microservices"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.hcltech.com/careers/java-developer-noida",
    description: "HCL's digital practice builds enterprise Java applications. Work on client projects across industries. Structured training and certifications."
  },
  {
    id: "j29",
    title: "React Developer (1-3)",
    company: "BrowserStack",
    location: "Mumbai",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "JavaScript", "Webpack", "Testing"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.browserstack.com/careers/react-developer",
    description: "BrowserStack powers cross-browser testing for developers. Build the dashboard and developer experience. Work on tools used by top tech companies."
  },
  {
    id: "j30",
    title: "SDE Intern",
    company: "Cred",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "React", "APIs"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://cred.club/careers/sde-intern-707",
    description: "CRED's internship offers high ownership from day one. Work on rewards, payments, or growth. Meritocratic culture, no hierarchy."
  },
  {
    id: "j31",
    title: "Graduate Engineer Trainee",
    company: "LTIMindtree",
    location: "Pune",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", ".NET", "Cloud", "DevOps"],
    source: "Indeed",
    postedDaysAgo: 10,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.ltimindtree.com/careers/get-pune",
    description: "LTIMindtree's GET program covers full-stack and cloud. Rotate across digital transformation projects. Strong training and mentoring."
  },
  {
    id: "j32",
    title: "Junior Backend Developer",
    company: "Groww",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Kotlin", "Spring", "PostgreSQL"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "6–10 LPA",
    applyUrl: "https://groww.in/careers/junior-backend-808",
    description: "Groww is India's investment platform. Build backend for stocks, mutual funds, and payments. Fintech scale and compliance exposure."
  },
  {
    id: "j33",
    title: "Frontend Intern",
    company: "Licious",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["React", "JavaScript", "HTML", "CSS"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.licious.in/careers/frontend-intern",
    description: "Licious delivers fresh meat and seafood. Work on e-commerce and logistics interfaces. Consumer product experience in D2C space."
  },
  {
    id: "j34",
    title: "QA Intern",
    company: "MakeMyTrip",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Selenium", "API Testing", "JIRA", "Postman"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://careers.makemytrip.com/qa-intern",
    description: "MakeMyTrip's QA team ensures travel booking reliability. Test flights, hotels, and payments flows. Exposure to high-traffic consumer product."
  },
  {
    id: "j35",
    title: "Data Analyst Intern",
    company: "Myntra",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["SQL", "Python", "Tableau", "Excel"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.myntra.com/careers/data-intern",
    description: "Myntra's analytics drives fashion and assortment decisions. Work on customer and inventory analytics. E-commerce data at scale."
  },
  {
    id: "j36",
    title: "Python Developer (Fresher)",
    company: "Thoughtworks",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "TDD", "Clean Code", "Agile"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.thoughtworks.com/careers/python-fresher",
    description: "Thoughtworks emphasizes craft and consulting. Freshers learn TDD, refactoring, and agile practices. Work on client projects across industries."
  },
  {
    id: "j37",
    title: "Java Developer (0-1)",
    company: "EPAM",
    location: "Hyderabad",
    mode: "Remote",
    experience: "0-1",
    skills: ["Java", "Spring", "Kubernetes", "AWS"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.epam.com/careers/java-0-1-india",
    description: "EPAM builds software for global enterprises. Work on cloud-native Java applications. Strong engineering practices and learning culture."
  },
  {
    id: "j38",
    title: "React Developer (1-3)",
    company: "CleverTap",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Redux", "TypeScript", "GraphQL"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "10–18 LPA",
    applyUrl: "https://clevertap.com/careers/react-developer",
    description: "CleverTap is a martech platform. Build dashboards and customer engagement UIs. B2B SaaS product with global customers."
  },
  {
    id: "j39",
    title: "SDE Intern",
    company: "Ola",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Kotlin", "Java", "Android", "Firebase"],
    source: "Indeed",
    postedDaysAgo: 7,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://ola.com/careers/sde-intern-909",
    description: "Ola's mobility and electric vehicle platforms. Interns work on app or backend systems. Impact on India's transportation ecosystem."
  },
  {
    id: "j40",
    title: "Graduate Engineer Trainee",
    company: "Tech Mahindra",
    location: "Chennai",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Python", "Automation", "Testing"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.techmahindra.com/careers/get-chennai",
    description: "Tech Mahindra's GET program covers software and automation. Work on telecom and enterprise projects. Certifications and upskilling support."
  },
  {
    id: "j41",
    title: "Junior Backend Developer",
    company: "Dream11",
    location: "Mumbai",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Node.js", "MongoDB", "Redis", "AWS"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "6–10 LPA",
    applyUrl: "https://dream11.com/careers/junior-backend-1010",
    description: "Dream11 runs India's largest fantasy sports platform. Build backend for real-time scoring and user systems. High concurrency, event-driven architecture."
  },
  {
    id: "j42",
    title: "Frontend Intern",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["React", "TypeScript", "Tailwind", "GraphQL"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://razorpay.com/jobs/frontend-intern-1111",
    description: "Build Razorpay's checkout and dashboard UIs. Work on payment flows used by millions of businesses. Modern React and TypeScript stack."
  },
  {
    id: "j43",
    title: "Data Analyst Intern",
    company: "OLA Electric",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "SQL", "Power BI", "Excel"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://olaelectric.com/careers/data-intern",
    description: "OLA Electric's data team supports manufacturing and sales. Build dashboards for operations and growth. EV and manufacturing analytics."
  },
  {
    id: "j44",
    title: "QA Intern",
    company: "Practo",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Manual Testing", "API Testing", "Appium", "JIRA"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://practo.com/careers/qa-intern",
    description: "Practo connects patients with healthcare. QA interns test doctor discovery and consultation flows. Healthcare domain exposure."
  },
  {
    id: "j45",
    title: "Python Developer (Fresher)",
    company: "VMware",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Automation", "Linux", "Networking"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "6–10 LPA",
    applyUrl: "https://careers.vmware.com/python-fresher-india",
    description: "VMware's software-defined infrastructure. Freshers work on automation and tooling. Enterprise software and cloud exposure."
  },
  {
    id: "j46",
    title: "React Developer (1-3)",
    company: "Dealshare",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "JavaScript", "Redux", "REST"],
    source: "Indeed",
    postedDaysAgo: 6,
    salaryRange: "10–18 LPA",
    applyUrl: "https://dealshare.in/careers/react-developer",
    description: "DealShare is social commerce for Bharat. Build consumer and seller web experiences. High growth, tier-2 and tier-3 focus."
  },
  {
    id: "j47",
    title: "SDE Intern",
    company: "MediaNet",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Java", "Python", "Databases", "APIs"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://medianet.com/careers/sde-intern",
    description: "Media.net powers contextual advertising. Work on ad serving or analytics systems. High-scale distributed systems exposure."
  },
  {
    id: "j48",
    title: "Junior Backend Developer",
    company: "Livspace",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Node.js", "PostgreSQL", "Redis", "AWS"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.livspace.com/in/careers/junior-backend",
    description: "Livspace is home interiors and renovation. Build backend for design tools and order management. Home-tech and supply chain exposure."
  },
  {
    id: "j49",
    title: "Graduate Engineer Trainee",
    company: "L&T Infotech",
    location: "Mumbai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Angular", "Cloud", "SQL"],
    source: "Naukri",
    postedDaysAgo: 10,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.lntinfotech.com/careers/get-mumbai",
    description: "L&T Infotech GET program covers enterprise applications. Work on digital transformation for large clients. Structured onboarding and training."
  },
  {
    id: "j50",
    title: "Frontend Intern",
    company: "Chargebee",
    location: "Chennai",
    mode: "Remote",
    experience: "Fresher",
    skills: ["React", "JavaScript", "CSS", "REST APIs"],
    source: "Indeed",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.chargebee.com/careers/frontend-intern",
    description: "Chargebee handles subscription billing for SaaS. Build dashboard and billing UIs. B2B SaaS and payments domain."
  },
  {
    id: "j51",
    title: "Java Developer (0-1)",
    company: "Intuit",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring", "Microservices", "AWS"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.intuit.com/careers/java-0-1-india",
    description: "Intuit builds TurboTax and QuickBooks. Work on tax and accounting products. Strong engineering culture and global impact."
  },
  {
    id: "j52",
    title: "Data Analyst Intern",
    company: "Ninjacart",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "SQL", "Excel", "Visualization"],
    source: "Indeed",
    postedDaysAgo: 7,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://ninjacart.in/careers/data-intern",
    description: "Ninjacart connects farmers to retailers. Analyze supply chain and logistics data. Agri-tech and impact-driven analytics."
  },
  {
    id: "j53",
    title: "React Developer (1-3)",
    company: "Simpl",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "TypeScript", "Node.js", "GraphQL"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "10–18 LPA",
    applyUrl: "https://getsimpl.com/careers/react-developer",
    description: "Simpl offers buy-now-pay-later. Build merchant and consumer web experiences. Fintech checkout and BNPL flows."
  },
  {
    id: "j54",
    title: "QA Intern",
    company: "Zomato",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Selenium", "API Testing", "Mobile Testing", "JIRA"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.zomato.com/careers/qa-intern",
    description: "Zomato's QA ensures food delivery reliability. Test restaurant, delivery, and payment flows. High-traffic consumer product testing."
  },
  {
    id: "j55",
    title: "SDE Intern",
    company: "Innovaccer",
    location: "Noida",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "React", "Healthcare", "APIs"],
    source: "LinkedIn",
    postedDaysAgo: 6,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://innovaccer.com/careers/sde-intern",
    description: "Innovaccer is healthcare data platform. Work on patient and provider applications. Healthcare tech and meaningful impact."
  },
  {
    id: "j56",
    title: "Junior Backend Developer",
    company: "Curefit",
    location: "Bangalore",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Python", "Django", "PostgreSQL", "Redis"],
    source: "Indeed",
    postedDaysAgo: 2,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.cure.fit/careers/junior-backend",
    description: "Curefit combines fitness and health. Build backend for classes, subscriptions, and nutrition. Health-tech and D2C experience."
  },
  {
    id: "j57",
    title: "Python Developer (Fresher)",
    company: "Rebel Foods",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Django", "SQL", "APIs"],
    source: "LinkedIn",
    postedDaysAgo: 8,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.rebelfoods.com/careers/python-fresher",
    description: "Rebel Foods runs cloud kitchens. Build systems for kitchen operations and delivery. Food-tech and logistics exposure."
  },
  {
    id: "j58",
    title: "Graduate Engineer Trainee",
    company: "Persistent",
    location: "Pune",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Angular", "Cloud", "DevOps"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.persistent.com/careers/get-pune",
    description: "Persistent's GET program covers software product development. Work on client projects in healthcare and tech. Strong training ecosystem."
  },
  {
    id: "j59",
    title: "Frontend Intern",
    company: "Acko",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["React", "JavaScript", "CSS", "APIs"],
    source: "Indeed",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://acko.com/careers/frontend-intern",
    description: "Acko is a digital insurance company. Build policy purchase and claims interfaces. Insurtech and consumer product experience."
  },
  {
    id: "j60",
    title: "React Developer (1-3)",
    company: "InMobi",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "TypeScript", "Redux", "Node.js"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.inmobi.com/careers/react-developer",
    description: "InMobi is a mobile advertising platform. Build dashboards and publisher tools. Ad tech at global scale."
  }
];
